os: linux
sudo: required
dist: trusty
language: c

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - devel

before_install:
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libssl-dev
  - wget https://red.libssh.org/attachments/download/121/libssh-0.6.5.tar.xz
  - tar -xJf libssh-0.6.5.tar.xz
  - mkdir libssh-0.6.5/build && cd libssh-0.6.5/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJf cmocka-1.0.1.tar.xz
  - mkdir cmocka-1.0.1/build && cd cmocka-1.0.1/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - git clone https://github.com/CESNET/libyang.git
  - mkdir libyang/build && cd libyang/build
  - git checkout devel
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

#env:
#  global:
#   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
#   #   via the "travis encrypt" command using the project repo's public key
#   - secure: ""

#addons:
#  coverity_scan:
#    project:
#      name: "CESNET/libnetconf2"
#    notification_email: rkrejci@cesnet.cz
#    build_command_prepend: "mkdir build ; cd build ; cmake .. ; make clean"
#    build_command: "make"
#    branch_pattern: coverity

script: 
  - mkdir build && cd build ; cmake .. && make -j2 && make test

